# Generated by Django 3.2.12 on 2024-01-24 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrimage', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_of_visit',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='Your Email', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Your Name', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('Suprabatha', 'Suprabatha'), ('Angapradakshina', 'Angapradakshina'), ('Thomala', 'Thomala'), ('Kalyanam', 'Kalyanam'), ('Bramhotsavam', 'Bramhotsavam')], default='Suprabatha', max_length=15),
        ),
    ]
