name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Docker
        run: sudo apt-get update && sudo apt-get install -y docker.io

      - name: Authenticate with GitHub
        run: echo "Authenticated with GitHub"

      - name: Authenticate with AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && aws configure set region us-east-1

      - name: Pull Docker image
        run: docker pull mahesh0404/templeimage_actions:latest

      - name: Run Docker container
        run: docker run -d -p 80:80 mahesh0404/templeimage_actions:latest
